### ISSUE TITLE
Packages become transiently unresolvable during a suite run: a test wipes dist/ mid-run

### ISSUE THREAD

**Issue by CodySwannGT** [CodySwannGT/lisa#3054]
Three sightings in one session of packages becoming **transiently unresolvable** while several checkouts of this repository ran work concurrently. Each time the missing thing was present again moments later, and each time the failure was reported as something other than what it was.

**This ticket reports the effect and deliberately refuses to name a mechanism.** Three sightings is enough to be worth investigating and not enough to conclude from. A named-but-wrong cause is worse than an open question — this campaign has already had three proposed mechanisms turn out wrong.

---

### 1 and 2 — `lint:slow`, two different `dist/` files, minutes apart

Both while a full suite ran concurrently. Both files present immediately afterwards, and the command passed on re-run with no change to the tree.

```
Error: ENOENT: no such file or directory, stat '…/dist/configs/vitest/typescript.d.ts'
Occurred while linting …/vitest.config.ts:14
Rule: "import/namespace"
```

```
Error: Cannot find module '…/dist/configs/eslint/slow.js'
  at createEsmNotFoundErr (node:internal/modules/cjs/loader:1419:15)
  … at /…/eslint.slow.config.ts:23:19
```

These surfaced through the push gate as:

```
❓ required gate NOT PROVED: code-style-slow — bun run lint:slow (exit 2) — no recognised failure signature
❓ required gate NOT PROVED: dead-code — bun run knip:check (exit 2) — no recognised failure signature
```

### 3 — `brace-expansion`, inside a concurrent test run

Two full suites started together at one commit. One reported `922 passed / 1 failed`, the failure being `tests/unit/hooks/parity-safety-net-heredoc-literal.test.ts > names git commit -F for commit-shaped heredoc denials`, with this immediately above it in the transcript:

```
Cannot find package 'brace-expansion'

  ⚠️  Lisa could not apply its templates to this project.
  The install SUCCEEDED — your dependencies are fine. What did not happen
  is the template and guardrail update Lisa normally performs here …
```

The assertion failure is downstream of that: the safety-net produced its generic message instead of the remediation text the case asserts on, because the hook could not resolve a dependency.

```
AssertionError: expected 'Blocked by safety-net: malformed or a…' to contain 'git commit -F <file>'
```

The file passes on its own.

## What is established

- All three happened while **multiple checkouts of this repository were running work at the same time**.
- In all three the missing file or package was **present immediately afterwards**, and the command succeeded on re-run with nothing changed.
- **No test in this suite rebuilds `dist/`.** Every `git grep` hit for `build:dist` / `clean-dist` in `tests/` is a string assertion about a package script, not an invocation.

## What is NOT established

- **Which process removed or replaced the file.** One candidate worth testing rather than believing: `vitest.config.ts` loads its globalSetup from the built package, and `bun run test`'s `pretest` runs `[ -d dist/configs ] || bun run build`, so a sibling checkout doing a build is a plausible source — and `scripts/clean-dist.mjs` deletes before `tsc` rewrites, which is a window. **That is a hypothesis, not a finding.** It was raised by someone who could see the other checkouts and could not see the timestamps.
- **Whether it is one mechanism or three.** Two are `dist/` artifacts of this repository; the third is a `node_modules` package.
- **Whether it can happen on a single-checkout machine or in CI**, where the concurrency that all three share is absent.

## The measurement that would settle it

Correlate the failure timestamps against the start and end times of any `bun run build` / `clean-dist.mjs` in every concurrent checkout. If they line up, this is concurrency and should be recorded as an operating constraint rather than a defect — with the fix being that a build must not be visible half-finished. If they do not, it stays open and unpinned.

## Why it is worth a ticket rather than a retry

Each sighting was reported as a content failure. `exit 2` with *"no recognised failure signature"*, and an assertion about remediation text — none of which says "a file vanished underneath me". An operator's rational response to all three is to re-run, and re-running works, so the real condition is never examined. That is the same shape as `exit 1` carrying two opposite facts (#3032), and the same reason it goes unlooked-at.

## Out of scope

- Naming a cause without the correlation above.
- Serialising the agent fleet. If concurrency is the condition, the answer is that a build not be observable in a partial state, not that only one thing may run.

**Comment by CodySwannGT** [comment]
[lisa-pr-link] https://github.com/CodySwannGT/lisa/pull/3060

**Comment by CodySwannGT** [comment]
## Two of the three are explained. Two claims in the description above are wrong, and both were mine.

Fixed in #3060. The mechanism below is **reproduced, not proposed** — and it is not the build-window-across-checkouts hypothesis this ticket carried.

---

### What actually happens

`tests/integration/cli-smoke.test.ts` runs `bun run build:dist` in a `beforeAll`, against the **real checkout**. `build:dist` opens with `clean-dist.mjs` — an `rm -rf` of the whole `dist/` — and `tsc` then rebuilds it file by file.

Polling for existence every 25 ms across one run of that file:

| file | absent for |
|---|---|
| `dist/index.js` | **5,218 ms** |
| `dist/configs/eslint/slow.js` | **5,143 ms** |
| `dist/configs/vitest/typescript.d.ts` | **5,168 ms** |

The second and third are the exact two files from sightings 1 and 2. Both of those `lint:slow` invocations ran while a full-suite run was in flight, and a full suite includes `tests/integration`.

The same probe over a `tsc`-only rebuild: **zero gaps**. And zero again over a full run of the smoke test after the fix, which still passes.

### Correction 1 — "No test in this suite rebuilds `dist/`" is false

I wrote that in the description above. It came from grepping `tests/` for the script name, opening **two of about twenty hits**, finding string assertions in both, and generalising to all twenty. The invocation is `run("bun", ["run", "build:dist"])`.

### Correction 2 — it is not cross-checkout

`clean-dist.mjs` resolves `dist` from **its own location**, so a sibling checkout's build cannot reach another one. The title's framing — "under concurrent checkouts" — is wrong. The concurrency that bites is **inside a single checkout**: the integration suite against anything else reading `dist/`.

### Both were already recorded here, twice

- `tests/integration/cli-smoke.test.ts`, in the comment immediately above the line changed: `build:plugins` "deletes and regenerates plugins/** in place … that rebuild intermittently removes plugins/** out from under unit tests reading those generated artifacts (**flaky ENOENT**)."
- `stryker.conf.json`: "**the integration suite rebuilds `dist/` while this runs**, so the sandbox scan lists `.d.ts` files that are gone by the time it reads them and the whole gate dies on ENOENT."

Two prior authors hit this shape and wrote it down. This ticket asserted the opposite. Worth noting as a process point: the repository already knew, and a keyword search of `tests/` did not find it because the knowledge lived in prose next to a config.

### Sighting 3 stays open

`Cannot find package 'brace-expansion'` inside a fixture is a `node_modules` resolution, not a `dist/` one. **Nothing in #3060 touches it**, and it is not folded into a mechanism that does not cover it. If it recurs, the thing to capture is which `node_modules` tree the resolution was rooted at and what was writing to it at that moment.

### Related surface, recorded rather than changed

Five `verify:*` scripts in `package.lisa.json` each run `bun run build:dist`, so each opens the same window. They are deliberate build-then-verify invocations rather than tests, so they are not concurrent with a suite in the way the smoke test is — but if any of them is ever run alongside other work, it has the same effect. Not changed blind.

---

## A separate observation from the same session, for #3032 rather than this ticket

Pushing #3060 took three attempts, and the two failures were **different tests, both passing standalone**:

1. `test-correctness` / `coverage-adequacy` — `bun run test:cov:unit` exited 1. Re-run standalone: **14,843 passed**, exit 0.
2. `tests/integration/coverage-scratch-debris.test.ts > sweeps the debris even when the run that sweeps it is killed`. Re-run standalone: passes in 10.0 s.

The second one is self-explaining, and its own assertion message says why:

> the target finished before the kill landed, so nothing was killed and this case proves nothing — give SLOW_RUN a larger target or raise KILL_AFTER_MS

That is a test refusing to pass **vacuously**, which is right — and it means a scheduling accident reds the gate. It took 15,452 ms under load against 10,022 ms standalone. It is a precondition failure, not a defect in what it covers, and it belongs to #3032's first clause rather than here. Recorded, not fixed: the remedy is the test author's to choose, and it is named in their own message.

**Comment by CodySwannGT** [comment]
**Title corrected.** It read "under concurrent checkouts", which is wrong and would have sent the next reader looking in the wrong place. `clean-dist.mjs` resolves `dist` from **its own location**, so a sibling checkout's build cannot reach another one — the concurrency that bites is **inside a single checkout**, between the integration suite and anything else reading `dist/`.

Recording the change rather than making it silently: the old title is what two of my own wrong claims were built on.

The placement problem this rediscovery exposed — that both prior records of this hazard were correct, adjacent to a config, and unreachable from where the symptom appears — is filed separately as #3061.

**Comment by CodySwannGT** [comment]
## Fourth sighting, and this one eliminates namespace contention as the explanation

Recorded as an observation. **No mechanism proposed** — the point of this note is
the control, not a theory.

### What happened

Pushing a single-commit branch (#3059, a new shipped helper plus its tests), the
pre-push gate failed twice on gates that pass standalone, then succeeded on the
third attempt with no change to the tree between attempts.

| attempt | gate that failed under the push gate | same command, run directly |
| --- | --- | --- |
| 1 | `test-integration` — "1 test(s) ran and failed" | **87 files / 1794 tests, all passing** |
| 2 | `coverage-adequacy` — "the runner executed ZERO test files" | **14,851 tests, all passing** |
| 3 | — | pushed |

The standalone runs were taken immediately after each failure, in the same
worktree, against the same commit.

### Why this sighting is worth adding

**`TMPDIR` was already isolated to a session-private scratchpad for all three
attempts**, and the isolated namespace was measured at **0 entries** while the
shared one sat at 470. So the usual explanation for this family — the shared
scratch namespace being over its ceiling because of concurrent fleet work — is
ruled out here rather than merely unlikely.

That is the whole contribution of this note. Everyone's first hypothesis for a
gate that fails under load and passes alone is namespace contention, and on this
occasion it cannot be that, because there was no shared namespace involved and
the private one was empty.

Attempt 2's message is also worth keeping verbatim, because it is a good
example of the reporting working: *"the runner executed ZERO test files, so
nothing it printed is a measurement — a coverage report from this run reads 0%
because no code was executed, NOT because coverage regressed. Whatever stopped
the run from starting is the failure."* The gate correctly refused to report a
coverage number it had not measured. What it could not say is why the run did
not start.

### What this shares with the existing sightings

Same family as the transient `dist/` disappearance and the `brace-expansion`
resolution failure already on this issue: **a step that fails on something
environmental, reports it as a content failure, and passes on retry with nothing
changed.** The common surface is "ran under concurrency, failed in a way that
names the wrong thing".

Not proposing that these share a root cause. Recording that they share a
signature, and that this instance has one explanation ruled out.

**Comment by CodySwannGT** [comment]
## Sighting — anecdote, not a reproduction

Flagging this explicitly as an **anecdote**: I did not capture which test failed, so this cannot be resolved into or out of the family from what I have. Adding it because a fifth data point costs nothing and a missing one might.

**What happened.** Pushing a branch, the pre-push gate refused:

```
❌ required gate FAILED: test-integration — bun run test:integration:push (exit 1) — 1 test(s) ran and failed
```

I ran the same command directly, seconds later, in the same worktree with no change to the tree:

```
Test Files  87 passed (87)
     Tests  1794 passed (1794)
  Duration  54.33s
```

Re-pushed with no change. Green.

**How it matches the family.** Transient, passes standalone immediately afterwards, no change to the tree between the two, and reported as a content failure — *"1 test(s) ran and failed"* — rather than as whatever it was. That last part is the same reporting shape as the `lint:slow` sightings surfacing through the push gate as `NOT PROVED — no recognised failure signature`.

**How it differs.** The three recorded sightings all name a *missing artifact* — two `dist/` files and `brace-expansion`. Mine names nothing; the gate line says a test ran and failed, and the failing test's identity is what I lost. So I cannot say whether a package was transiently unresolvable here or whether one test genuinely failed for an unrelated reason.

**Concurrency was present**, which is the one thing this shares with all three: another checkout of this repository was running a Stryker campaign throughout, and a separate worktree of mine had been running suites minutes earlier. I did not record whether anything was mid-`build:dist` at that moment.

**What I did not capture, so the next person does not assume I did:** the failing test's name, the transcript above the gate line, and whether `dist/` was intact at the moment of failure. The gate's own summary line was all I kept.

Per guidance from the session coordinating this campaign I am **not** attempting to reproduce it — an honest anecdote in the right ticket beats an hour spent chasing a fifth sighting whose mechanism may already be the one that is pinned and fixed.

**Comment by CodySwannGT** [comment]
## Fifth data point — observation, not a reproduction

Recorded while working #3029. **No mechanism proposed**, and I have not tried to
resolve it into or out of the family. What makes it worth a line is that this
sighting behaves *unlike* the others in one specific way, which may be the more
useful half.

### What happened

Two suites fail locally on this branch and pass on a clean tree:

```
tests/unit/scripts/derived-artifact-staleness.test.ts > passes on a tree whose artifacts are current
tests/unit/scripts/invoked-as-script.test.ts        > BITE: the pre-commit artifact gate reaches its verdict through a symlink
```

Both spawn `check-derived-artifacts.mjs` against the **real repo** (`cwd: repoRoot`).

### The flakiness demonstrating itself

Three consecutive runs of the same file, same tree, nothing changed between them:

| run | load average | result |
| --- | --- | --- |
| 1 | 114 | failed |
| 2 | 95 | **passed** |
| 3 | 73 | failed |

And in one full-suite run `derived-artifact-staleness` **passed** while
`coverage-scratch-debris` failed; in the previous run it was the other way round.

### The control that exonerates the branch

The gate short-circuits in **~80 ms** on a clean tree, but does the full ledger
walk whenever an artifact is staged. On a **pristine `origin/main` tree with one
trivial staged comment** it took **58 s** — *slower* than this branch's 20–34 s.
So "a staged artifact change" is the condition, not "this branch's diff".

### Why this one is different from the other four

Every earlier sighting here was **misreported as a content failure** — `exit 2`
with "no recognised failure signature", an assertion about remediation text.
This one was not:

```
Error: check-derived-artifacts.mjs --staged did not complete: spawnSync … ETIMEDOUT.
Its budget was scaled by a measured 1.86x spawn slowdown, so this is a real hang
or a machine past 8x — not ordinary variance. See tests/helpers/io-latency-budget.ts.
```

`boundedSpawnSync`'s `assertChildCompleted` named the kill, named the scaling it
had already applied, and said which of the two facts the failure carried. That is
the diagnostic the other four sightings were missing, working — so if the family
does turn out to be one thing, the fix for the *reporting* half may already exist
and just need reaching further.

I did not touch the budget or the assertion.

**Comment by CodySwannGT** [comment]
## Hypothesis with a test: this may be ONE defect seen through call sites that were not yet bounded

Following the fifth data point above. **This is a hypothesis, not a finding** — it
is stated so it can be falsified cheaply, because if it holds it changes what this
ticket is asking for.

### The claim

The four earlier sightings may not be four mechanisms. They may be **one condition
— a child that does not complete under contention — observed through four call
sites that had no deadline and no completion assertion**, so each surfaced as
whatever its caller happened to check next:

| sighting | what it reported | what it may actually have been |
| --- | --- | --- |
| 1, 2 | `exit 2`, "no recognised failure signature" | a child that did not complete |
| 3 | an assertion about remediation text | a child that did not complete |
| 4 | "1 test(s) ran and failed", passing standalone | a child that did not complete |
| 5 (mine) | **`ETIMEDOUT`, naming the kill and the 1.86x scaling already applied** | a child that did not complete |

The fifth is the only one that said so, and the only difference is that its call
site goes through `boundedSpawnSync`, whose `assertChildCompleted` names the kill
rather than letting the empty streams read as a content mismatch.

### Why it is worth testing

If it holds, **the reporting half of this ticket is already solved** and needs
*propagating*, not diagnosing. That reframes the work from "find the mechanism"
— which four sightings have not yielded — to "finish routing child starts through
the bounded helper", which is mechanical and enumerable. It would also explain the
thing this ticket keeps noting: that every sighting was reported as something other
than what it was. An unbounded `spawnSync` killed from outside returns **empty
streams**, so the failure necessarily arrives wearing a content failure's clothes.

### The test that would settle it

Cheap and decisive, in this order:

1. **Enumerate** the synchronous child starts on the paths the four sightings ran
   through, and check which are bounded. `tests/unit/helpers/unbounded-spawn-conformance.test.ts`
   already does this for the tracked test tree and reports zero — so the question
   is specifically about the **non-test** call sites: the gate scripts and the
   push-gate runners the four sightings went through.
2. **Route one of them** through `boundedSpawnSync` and re-run under load.
3. If the failure then arrives **naming a timeout instead of a content mismatch**,
   the sighting was this condition wearing a disguise. If it still arrives as a
   content failure, the hypothesis is dead for that call site and this comment
   should be struck.

Step 3 is the falsifier. It does not require reproducing the original failure —
only observing that the *same* failure changes its report once bounded.

### What this does not claim

- It does **not** claim to explain sightings 1 and 2, whose mechanism is already
  reproduced and fixed in #3060 (`cli-smoke.test.ts` running `build:dist` against
  the real checkout). Those are settled and are not evidence for this.
- It does **not** name a cause for the remaining sightings. "A child did not
  complete" is a *description of the failure*, not a mechanism — what starves the
  child is still open.
- It is raised by someone who has read four sightings and reproduced none of them.

**Comment by CodySwannGT** [comment]
## Known false signature: `code-style-slow` + `dead-code` failing together can be a local worktree, not this family

Recording a sighting I **did not** add to this ticket, because checking it took two minutes and it turned out to be mine. Posting it so the next person who sees this exact pair does the same check first.

### What it looked like

A push refused with precisely this ticket's shape — two gates failing with no recognised failure signature, both passing standalone:

```
❓ required gate NOT PROVED: code-style-slow — bun run lint:slow (exit 2) — no recognised failure signature
❓ required gate NOT PROVED: dead-code    — bun run knip:check (exit 2) — no recognised failure signature
```

Same two gates, same `exit 2`, same "no recognised failure signature" as sightings 1 and 2 above. On the evidence in the push output alone it is indistinguishable from a member of this family.

### What it actually was

**A worktree with no `dist/` and a symlinked `node_modules`.** I had created a scratch worktree and symlinked `node_modules` from a sibling rather than installing. `eslint.slow.config.ts` imports Lisa's own built config through the package's self-reference, so with no `dist/configs` present locally the resolution walked the symlink into the *sibling* worktree and failed there:

```
at /Users/…/wt-A/eslint.slow.config.ts:23:19
at jitiResolve (/Users/…/wt-B/node_modules/jiti/dist/jiti.cjs…)
```

A real `bun install` plus `bun run build` in that worktree fixed it completely, and the push then failed on something else entirely (a parity pin), which is how I knew.

### The check that distinguishes them, before adding a sighting

```
ls dist/configs        # absent -> local setup, not this family
ls -l node_modules     # a symlink -> resolution can escape this worktree
```

If `dist/configs` is missing, or `node_modules` is a symlink to another checkout, that is sufficient to explain both gates and the sighting does not belong here.

### Why it is worth a line

This family is defined by *transient* unresolvability — a file present again moments later. The failure above is **permanently** unresolvable until the worktree is set up properly, and it is only the *reporting* that makes them look alike: both surface as `exit 2` with no recognised signature, because neither gate's output matches a known pattern.

That is worth knowing in its own right. **"No recognised failure signature" is not evidence of this family** — it is evidence that the runner could not classify the failure, and a mis-set-up worktree produces exactly that. A ticket that accumulates unrelated members because they share an unclassified exit code gets harder to solve with every addition.

**Comment by CodySwannGT** [comment]
## Grooming: stalled, returned to the ready queue

Checked as part of a queue-drain pass. This item is labelled `status:in-progress` but nothing is in progress on it:

- no open pull request references it
- no branch carries unpushed work for it
- its most recent activity is a recorded sighting, not an attempt

Its named PRs merged, but they closed **part** of the scope — the acceptance criteria carried in the body are not all met, which is what the body itself says. `status:in-progress` on an item with no active attempt reads to every scanner as "someone has this", so it is skipped by the intake that would otherwise pick it up. That is how a stalled item becomes an invisible one.

Moved to `status:ready` so it is dispatchable again. No scope was changed and nothing was closed.

**Comment by CodySwannGT** [comment]
[lisa-pr-link] https://github.com/CodySwannGT/lisa/pull/3187

**Comment by CodySwannGT** [comment]
## Sighting 3 is eliminated. The `brace-expansion` message is a test fixture, and nothing was unresolvable.

Fixed in #3187, but the elimination below matters more than the fix and stands on its own.

### `Cannot find package 'brace-expansion'` is not a missing package

It is a hardcoded `console.error` string inside a test fixture. `tests/unit/scripts/lisa-postinstall.test.ts`, the `project("fail")` stub, writes a stand-in Lisa entry point whose entire body is:

```js
console.error("Cannot find package 'brace-expansion'");
process.exit(1);
```

The postinstall under test then relays that stderr and prints the *"⚠️ Lisa could not apply its templates to this project. The install SUCCEEDED — your dependencies are fine…"* block — the same block quoted in the sighting — because printing it on a failed apply **is the behaviour being asserted**.

Measured by running that file alone:

```
Cannot find package 'brace-expansion'
  ⚠️  Lisa could not apply its templates to this project.
  The install SUCCEEDED — your dependencies are fine. What did not happen
…
 Test Files  1 passed (1)
      Tests  9 passed (9)
```

**Exit 0. Nine of nine passing. Both strings emitted twice.** The fixture landed 2026-08-19 (`c850361dc`), five days before the sighting.

So the description's causal chain for sighting 3 is false in both halves: no package was unresolvable, and *"the safety-net produced its generic message … because the hook could not resolve a dependency"* is not what happened. **The `node_modules` limb of "whether it is one mechanism or three" closes.** This family is `dist/`-and-friends only.

**The general lesson is the one worth keeping.** vitest interleaves stderr from concurrent workers, so *"immediately above it in the transcript"* carries **no** causal information. The inference here was adjacency, and the adjacent text was a passing test's deliberate output.

---

## What DID produce sighting 3's assertion, reproduced

The actual failure was:

```
expected 'Blocked by safety-net: malformed or a…' to contain 'git commit -F <file>'
```

`block_heredoc` chooses between two remediation texts by grepping the command for a git-commit shape, under `set -euo pipefail`:

```bash
if printf '%s' "$command_str" | grep -Eq -- '<git commit shape>'; then
```

grep answers **three** ways — `0` matched, `1` no match, `>=2` could not do the job — and a condition reads two. With a grep that exits 2, the hook prints the **Write-tool** remediation for a command that is a commit: the reported failure, byte for byte.

### And the same defect makes the safety net fail OPEN

Every built-in guard reaches its verdict the same way. Measured, with a `grep` that exits 2 first on PATH:

| command | real grep | grep cannot answer |
|---|---|---|
| `rm -rf /` | BLOCKED (2) | **ALLOWED (0)** |
| `git push --force origin main` | BLOCKED (2) | **ALLOWED (0)** |
| `dd of=/dev/disk0` | BLOCKED (2) | **ALLOWED (0)** |
| `git branch -D main` | BLOCKED (2) | **ALLOWED (0)** |

Silently, exit 0. The reasoning was already at the bottom of that same file for the *project custom rules* — a malformed ERE used to silently disable a rule the project believed it had — and was never extended to the built-ins.

**This is this ticket's thesis at its worst: the environmental failure's report was the word "safe".**

---

## The environmental condition, measured

```
ps -u $(id -u) | wc -l          ->  10527
sysctl -n kern.maxprocperuid    ->  10666
```

**98.7% of the per-user process cap**, with **7,679 orphaned `sleep 7200` processes parented to PID 1** — 72% of the whole cap held by watchdog sleeps whose parents are gone. `7200000` ms is `BASH_MAX_TIMEOUT_MS`. At that saturation `fork()` returns EAGAIN, and a grep that cannot start is a grep that cannot answer.

They have since been reaped. **The leak that produces them is not fixed and wants its own ticket** — it is an operating constraint that silently corrupts every measurement taken on this machine.

---

## `spawnSync <cmd> ENOENT` does not mean the command is missing

This changes how every sighting on this issue should be read.

```
cwd removed        -> ENOENT | spawnSync /bin/bash ENOENT
binary absent      -> ENOENT | spawnSync /bin/bash-not-here ENOENT
```

A removed **working directory** produces a byte-identical message naming the **command**. Observed 8 times in one loaded run, for a `/bin/bash` that plainly exists.

Two consequences:

1. An `ENOENT` in this family is **not evidence about the thing it names**.
2. *"The missing file was present again immediately afterwards"* — the observation all three original sightings share, and the reason the description calls them transient — is fully consistent with the file **never having been absent**.

**Which process removes the cwd is not established, and I am deliberately not naming one.** The run-root reclaim in `src/configs/vitest/scratch.ts` was examined and does not obviously do it: its age arm is a documented 6-hour backstop, and its liveness arm cannot make a live pid look dead. That stays open.

---

## Eliminated, so nobody re-runs them

- **The description's own cross-checkout `dist/` build-window hypothesis.** Already dead per #3060 — `clean-dist.mjs` resolves `dist` from its own location. Re-confirmed, not re-litigated.
- **SIGPIPE under `pipefail` on `printf | grep -q`.** My hypothesis, and it is dead. Structurally impossible below the pipe buffer — `printf` is a bash builtin and completes its write before `grep` can match — and measured at **0 occurrences in 4,000 iterations** at rest and under 24 CPU hogs, plus 0 across 200 runs at payloads from 1 KiB to 1 MiB.

---

## Concurrency measurements

Same tree, same command (`bun run test -- tests/unit/hooks`), four runs:

| run | processes (cap 10,666) | load avg | result |
|---|---|---|---|
| 1 | ~8,800 | 20 | 6 failed |
| 2 | 10,527 (98.7%) | 24 | 19 failed / 12 files |
| 3 | ~1,200 (mid-reap churn) | 26 | 177 failed / 7 files |
| 4 | 1,204 | **157** | **0 failed, 1359 passed** |

**Run 3 does not fit a clean story and I am recording it as-is rather than dropping it.**

What runs 1, 2 and 4 support is narrower, and it is worth stating exactly: **load average is not the discriminator.** Run 4 was the most loaded of the four and the only fully green one. Runs 1 and 2 reported every failure as `AssertionError` — not one said "resource" or "timeout" — in *different tests each time*, spanning `commit-msg`, `verification-gate` and `block-direct-issue-create`, none of which the fix touches.

---

## Recorded, not changed

`plugins/lisa/hooks/parity-safety-net.sh` is absent for **878 ms** during `bun run build:plugins`, and `plugins/lisa-codex/.codex-plugin/plugin.json` for **10,904 ms** of the 10.9 s build — the `plugins/` analogue of the `dist/` window #3060 closed. `pretest` (`[ -d dist/configs ] || bun run build`) is a check-then-act two concurrent suites in one checkout can both pass, and `bun run build` ends in `build:plugins`.

**No sighting here is pinned to that**, so it is measured and left alone rather than fixed blind.

`track-plan-sessions.sh:136` has the same `grep -q` shape, but its failure direction is a duplicate write rather than a wrong verdict. Left alone.

---

## What remains open on this ticket

- Which process removes a spawn's `cwd` under concurrency.
- Sightings 4 and 5, and the anecdote — none of them resolved into or out of this family here.
- The orphaned-watchdog leak, which is an operating constraint rather than a defect in this repository.

**Comment by CodySwannGT** [comment]
**The fail-open defect found here is now filed on its own as #3188**, with the shim reproduction and the five-row table in the body.

Filed separately rather than folded in because it is a different defect from this ticket's subject. #3054 is about packages becoming transiently unresolvable; #3188 is a shipped guard that permits a root recursive delete whenever `grep` cannot answer. It was found *under* this ticket — it reproduces sighting 3's assertion exactly — but it should not be discoverable only by reading this ticket's history.

The fix in flight (#3187) carries this ticket's Work-Item trailer and closes both surfaces.

**Comment by CodySwannGT** [comment]
## PR #3187 merged as `3d5ce120`, verified an ancestor of `main`

### Sighting 3 is eliminated, decisively

`Cannot find package 'brace-expansion'` is **not a missing package.** It is a hardcoded `console.error` string inside a test fixture — `tests/unit/scripts/lisa-postinstall.test.ts:53`, the `project("fail")` stub — printed to shared stderr by a **PASSING** test. Measured: exit 0, 9/9 passed, the exact text plus the whole "Lisa could not apply its templates" block emitted twice. The fixture landed 2026-08-19, **five days before the sighting.**

So this ticket's causal chain for sighting 3 is false, and the `node_modules` limb of "one mechanism or three" closes with it.

### What actually produced sighting 3's assertion — and it is far more serious than this ticket

Every built-in guard in `parity-safety-net.sh` reached its verdict through a `printf` piped into `grep -q` under `set -euo pipefail`. **grep answers three ways — 0 matched, 1 no match, ≥2 could not do the job — and a shell condition reads two.**

I reproduced this independently against main's shipped hook, with a `grep` shim on PATH that exits 2. Five catastrophic commands — a recursive delete of the filesystem root, a force-push over `main`, a raw write to `/dev/disk0`, a forced delete of the `main` branch, and a recursive delete of the home directory — were **BLOCKED with a working grep and ALLOWED with the shim.** Five for five, exit 0, silent.

**The safety net failed OPEN whenever grep could not answer** — and grep exits 2 for more reasons than a failed fork: an unreadable input, a regex the engine rejects. Verified fixed on the branch: all five blocked under the shim, with the negative controls still allowing ordinary work.

Filed separately as **#3188**, so it is discoverable on its own rather than only by reading this ticket's history.

### Two hypotheses eliminated, recorded so nobody re-runs them

- The cross-checkout `dist/` build-window hypothesis this ticket offered — already dead per #3060, and `clean-dist.mjs` resolves from its own location.
- SIGPIPE-under-`pipefail` on the printf-into-grep pipeline — structurally impossible for payloads under the pipe buffer; 4,000 iterations at rest and under 24 CPU hogs gave zero.

### Machine condition during this work

A saturation event was reported mid-investigation — 10,527 processes against a 10,666 per-uid cap. I measured before acting and **declined a reap**: by then it read 1,142 processes and 6 orphaned watchdog sleeps, so there was nothing worth killing.

Worth recording as a condition that makes any measurement on this box unreliable: under saturation, suites fail with plain `AssertionError` and **nothing anywhere says "resource"** — two runs of `tests/unit/hooks` gave 6 then 19 failures in *different* tests. That is this ticket's own signature.

Staying open: the original transient-unresolvability effect is not closed by this.

**Comment by CodySwannGT** [comment]
## Grooming — moving back to `status:ready`: nobody is working this, and part of it is genuinely unfinished

This has carried `status:in-progress` since the last substantive update with **no agent assigned to it.** In-progress and unattended are different states, and conflating them is how a ticket sits for a week looking busy. Correcting the label rather than the record.

### What is settled

**Sighting 3 is eliminated decisively**, and its causal chain here was false: `Cannot find package 'brace-expansion'` is a hardcoded `console.error` string in a passing test fixture, not a missing package. PR #3187 merged as `3d5ce120`. The `node_modules` limb of "one mechanism or three" closes with it.

That investigation also produced #3188 — every verdict site in `parity-safety-net.sh` reading `grep`'s three-way exit as two, so a `grep` that could not run made the guard **permit** catastrophic deletes. Filed, fixed, and verified separately, which is why it is not carried here.

### What is not

**The core effect this ticket is named for.** Packages becoming transiently unresolvable during a suite run because something wipes `dist/` mid-run has not been reproduced-then-fixed. Eliminating one sighting's explanation is not the same as eliminating the effect, and I would rather this re-enter the queue honestly than close on the strength of the limb that did resolve.

Anyone picking this up: **the remaining question is narrow.** Which suite writes to or removes `dist/` while another is resolving from it, and does it still happen on current `main`? Reproduce before designing anything — the sighting that produced this ticket has already been shown to have a different cause than assumed once.

**Comment by CodySwannGT** [comment]
[lisa-intake-blocked]

This item is paused because the originally identified destructive test path has already been fixed, while the remaining failure has not been reproduced on the current release. To make it ready, please provide: the priority; a current v4.23.26 reproduction with environment, frequency, and failure evidence; and the exact remaining writer and reader paths. If it cannot be reproduced, please choose whether this should become a bounded investigation or be closed as fixed.

**Comment by CodySwannGT** [comment]
Reproduced a current shared-build failure while running the full integration suite for #4044: `cli-smoke.test.ts` could not import `loadConfigState` from built `dist/health/deterministic-inputs.js`; the export was present immediately afterward, and the isolated three-test smoke suite passed unchanged.

The current sources reveal two remaining writes to shared build output during the suite: both CLI smoke and enforcement-census tests rebuild the real checkout in `beforeAll`. The package test runner already builds before launching Vitest. The logs do not identify which of those writers overlapped the failed import, so that attribution remains an inference. The packed-bin fixture builds its own isolated checkout.

Removed both redundant rebuilds, their unused helper, and four tests that pinned the earlier in-place-rebuild workaround. This removes 176 net lines while retaining actual CLI/census behavior checks; all 14 passed together. The normal build and the isolated packed-bin build remain. Independent review passed; full submission checks are running. This repair will share the test-reliability PR with #4044.

**Comment by CodySwannGT** [comment]
[lisa-pr-link] https://github.com/CodySwannGT/lisa/pull/4168

**Comment by CodySwannGT** [comment]
The unchanged baseline reproduced the shared-build race again while validating the #3685 test cleanup: `cli-smoke.test.ts` ran `bun run build:dist:in-place`, and `copy-codex-scripts.mjs` failed with `ENOTEMPTY` while removing `dist/codex/scripts` during concurrent integration tests. That submission passed 24,272 unit tests but its integration suite failed; it has not been submitted as green.

PR #4168 already removes the redundant integration-time builds and preserves the prepared CLI smoke checks. Its latest local submission passed 24,260 unit tests and 2,999 integration tests. The dependent cleanup will integrate this change after it lands before repeating full validation. No extra lock or retry mechanism is being added for this race.

**Comment by CodySwannGT** [comment]
Published the shared-build race correction in @codyswann/lisa 4.55.22 through PR #4168. Merge 7eca2c2799c603f9978987af3ecb94e9770a6058 is an ancestor of registry gitHead b33875d0fe28bbf7a5e1fe37ef71821e58b5b4ab. Release and Deploy run 34725248385 succeeded, including npm publication and post-deploy gates.

The two redundant integration-time builds and their obsolete helper/workaround tests are removed; CLI smoke checks use the build already prepared by the test runner. Final submission checks passed 24,260 unit tests (two skipped), 2,999 integration tests, type checks and generated artifact checks. The unchanged older baseline also reproduced the directory-removal race during this session, as recorded above.
